import "~/styles/globals.css";

import { type Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Modern site",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
    return (
        <nav className={"flex h-full justify-between items-center p-4 px-8 p border-b"}>
            <div>
                <Link href={"https://ethereum.org/en/"} target={"_blank"} rel={"noopener norefferer"}>Ethereum Site</Link>
            </div>
            <div>
                Sign in
            </div>
        </nav>
    );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        {children}
      </body>
    </html>
  );
}